project_name: plugindemowasm-http-call
version: 2

builds:
  - binary: plugin
    no_unique_dist_dir: true
    main: .
    ldflags:
      - ''
    targets:
      - wasip1_wasm
    buildmode: c-shared
    gobinary: ./gopath/bin/gotip

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^chore(deps):'
      - '^test:'
      - '^tests:'

archives:
  - id: plugindemowasm-http-call
    name_template: '{{ .ProjectName }}_v{{ .Version }}'
    format: zip
    files:
      - LICENSE
      - .traefik.yml
